name: frontend
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  fluid_bottom_nav_bar: ^1.3.0
  hexcolor: ^2.0.7
  google_fonts: ^3.0.1
  flutter_svg: ^0.22.0
  dropdown_button2: ^1.7.1
  fluttertoast: ^8.0.9
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0
  http: ^0.13.5
  web3dart: ^2.3.5
  web_socket_channel: ^2.2.0
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.2
  web3_connect: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Mulpay_Icon_2.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/MulPay_Icon_2_foreground.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
    - smartcontracts/

